#!/usr/bin/env bash

FQDN_OR_IP=192.168.56.102
#NGINX_CONF_FILE=pam-nginx.conf
NGINX_CONF_FILE=pam-nginx-ssl.conf

sed 's/FQDN_OR_IP/'${FQDN_OR_IP}'/g' $NGINX_CONF_FILE > nginx.conf

docker exec -ti pam-nginx cp /home/docker/pamweb/nginx.conf /etc/nginx/conf.d/default.conf
docker exec -ti pam-nginx nginx -s reload

exit 0;